version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  myblog: 
    build: ./myblog
    container_name: myblog_c
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./myblog
        target: /app
      - /app/node_modules
    stdin_open: true
    tty: true